POST http://127.0.0.1:5000//create_new_game/<int:id>
Content-Type: application/json

{}

###
POST http://127.0.0.1:5000/login
Content-Type: application/json

{
  "user_id": 4,
  "password": "Bisa"
}

###
POST http://127.0.0.1:5000/register
Content-Type: application/json

{
  "user_id" : 4,
  "password" : "Bisa"
}



